#!/usr/bin/perl
# vim:ts=4:sw=4:expandtab
# © 2013 Michael Stapelberg <stapelberg@debian.org>
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of Michael Stapelberg nor the
#       names of contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# .
# THIS SOFTWARE IS PROVIDED BY Michael Stapelberg ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL Michael Stapelberg BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=head1 NAME

deb-systemd-invoke - wrapper around systemctl, respecting policy-rc.d

=head1 SYNOPSIS

B<deb-systemd-invoke> [B<--user>] start|stop|restart S<I<unit file> ...>
B<deb-systemd-invoke> [B<--user>] [B<--no-dbus>] daemon-reload|daemon-reexec

=head1 DESCRIPTION

B<deb-systemd-invoke> is a Debian-specific helper script which asks
/usr/sbin/policy-rc.d before performing a systemctl call.

B<deb-systemd-invoke> is intended to be used from maintscripts to manage
systemd unit files. It is specifically NOT intended to be used interactively by
users. Instead, users should run systemd and use systemctl, or not bother about
the systemd enabled state in case they are not running systemd.

=cut

use strict;
use warnings;
use Getopt::Long; # in core since Perl 5
use IO::Socket::UNIX; # in core since at least Perl 5.6.1-8.9

if (@ARGV < 1) {
    print STDERR "Syntax: $0 <action> [<unit file> [<unit file> ...]]\n";
    exit 1;
}

my $is_system = 1;
my $use_dbus = 1;
my $result = GetOptions(
    "user" => sub { $is_system = 0; },
    "system" => sub { $is_system = 1; }, # default
    "no-dbus" => sub { $use_dbus = 0; },
);

# Varlink methods are very new, so check if the sockets and the methods are available
# to allow graceful fallbacks to older IPCs. Returns 0 when the calls could be made,
# -1 otherwise. This implementation must only use core Perl, and no external programs,
# to be self-contained and safe against apt ordering bugs.
sub varlink_method_invoke {
    my ($qualified_method, $parameters) = @_;
    my @sockets = ();

    # Split qualified method into interface and method name (e.g., "io.systemd.Manager.Reload" -> "io.systemd.Manager" and "Reload")
    my ($interface, $method) = $qualified_method =~ /^(.+)\.([^.]+)$/;
    if (!defined $interface || !defined $method) {
        die("Invalid qualified method: $qualified_method");
    }

    if ($is_system) {
        push @sockets, '/run/systemd/io.systemd.Manager';
    } else {
        # For each <UID> directory under /run/user/ check if the systemd/io.systemd.Manager socket exists
        opendir(my $dh, '/run/user/') || return;
        while (my $entry = readdir($dh)) {
            next if ($entry =~ /^\./); # skip . and ..
            my $socket_path = "/run/user/$entry/systemd/io.systemd.Manager";
            if (-S $socket_path) {
                push @sockets, $socket_path;
            }
        }
        closedir($dh);
    }
    return -1 if (! @sockets);

    # First check to see if the interface supports the method
    my $introspection_client = IO::Socket::UNIX->new(Type => SOCK_STREAM(), Peer => $sockets[0], Timeout => 30);
    return -1 if (! defined $introspection_client);
    $introspection_client->setsockopt(SOL_SOCKET, SO_RCVTIMEO, pack('l!l!', 30, 0)) or die "Failed to set socket receive timeout: $!";
    $introspection_client->setsockopt(SOL_SOCKET, SO_SNDTIMEO, pack('l!l!', 30, 0)) or die "Failed to set socket send timeout: $!";

    print $introspection_client "{\"method\":\"org.varlink.service.GetInterfaceDescription\",\"parameters\":{\"interface\":\"$interface\"}}\0";
    local $/ = "\0"; # set input record separator to null byte as per varlink protocol
    my $response = <$introspection_client>;
    close($introspection_client);
    return -1 if ($response !~ /method\s+$method\s*\(/);

    for my $socket (@sockets) {
        my $client = IO::Socket::UNIX->new(Type => SOCK_STREAM(), Peer => $socket, Timeout => 30);
        return -1 if (! defined $client);
        $client->setsockopt(SOL_SOCKET, SO_RCVTIMEO, pack('l!l!', 30, 0)) or die "Failed to set socket receive timeout: $!";
        $client->setsockopt(SOL_SOCKET, SO_SNDTIMEO, pack('l!l!', 30, 0)) or die "Failed to set socket send timeout: $!";

        print $client "{\"method\":\"$qualified_method\",\"parameters\":$parameters}\0";
        local $/ = "\0"; # set input record separator to null byte as per varlink protocol
        # wait for a reply, so that Reloads are synchronous
        my $response = <$client>;
        close($client);

        # Reexecute causes the socket to be closed with no response on reexec
        return -1 if ((! defined $response && $method ne "Reexecute") || (defined $response && $response =~ /"error"\s*:/));
    }

    return 0;
}

sub get_instances {
    my @instances = ();

    if (!$is_system) {
        # '--machine <ID>@' was added in v250 and v249.10, before that we can't talk to arbitrary user instances
        my $systemctl_version = `systemctl --version --quiet | sed -n -r "s/systemd ([0-9]+) \\(.*/\\1/p"`;
        chomp ($systemctl_version);
        if (system('dpkg', '--compare-versions', $systemctl_version, 'ge', '249') != 0) {
            print STDERR "systemctl version $systemctl_version does not support acting on user instance, skipping\n";
            return ();
        }

        # Each user instance of the manager has a corresponding user@<id>.service unit.
        # Get the full list of IDs, so that we can talk to each user instance to start/stop
        # user units.
        @instances = `systemctl --no-legend --quiet list-units 'user@*' | sed -n -r 's/.*user@([0-9]+).service.*/\\1/p'`;
    } else {
        push @instances, 'system';
    }

    return @instances;
}

sub do_start_restart {
    my ($action, @units) = @_;
    my @instances = get_instances();
    return if (!@instances);

    for my $instance (@instances) {
        my @instance_args = ();
        my @start_units = ();

        if ($instance eq 'system') {
            push @instance_args, '--system';
        } else {
            chomp ($instance);
            push @instance_args, '--user', '--machine', "$instance@";
        }

        for my $unit (@units) {
            my $unit_installed = 0;
            my $enabled_output = `systemctl @instance_args is-enabled -- '$unit'`;
            # matching enabled and enabled-runtime as an installed non static unit
            if ($enabled_output =~ /enabled/) {
                $unit_installed = 1;
            }
            system('systemctl', @instance_args, '--quiet', 'is-active', '--', $unit);
            my $unit_active = $?>>8 == 0 ? 1 : 0;
            if (!$unit_installed && $action eq "start") {
                print STDERR "$unit is a disabled or a static unit, not starting it.\n";
            } elsif (!$unit_installed && !$unit_active && $action eq "restart") {
                print STDERR "$unit is a disabled or a static unit not running, not starting it.\n";
            }
            else {
                push @start_units, $unit;
            }
        }
        if (@start_units) {
            system('systemctl', '--quiet', @instance_args, $action, @start_units) == 0 or die("Could not execute systemctl: $?");
        }
    }
}

sub do_stop_user {
    my ($action, @units) = @_;
    my @instances = get_instances();
    return if (!@instances);

    for my $instance (@instances) {
        chomp ($instance);
        system('systemctl', '--quiet', '--user', '--machine', "$instance@", $action, @units);
    }
}

sub reload_reexec_dbus {
    my ($action) = @_;
    my @instances = get_instances();
    return if (!@instances);

    for my $instance (@instances) {
        chomp ($instance);
        if ($instance eq 'system') {
            system('systemctl', '--quiet', '--system', $action);
        } else {
            system('systemctl', '--quiet', '--user', '--machine', "$instance@", $action);
        }
    }
}

sub reload_reexec_signal {
    my ($action) = @_;
    my $signal;

    if ($action eq "daemon-reload") {
        $signal = 'SIGHUP';
    } else {
        $signal = 'SIGRTMIN+25';
    }

    if ($is_system) {
        system('kill', '-s', $signal, '1');
    } else {
        system('systemctl', '--quiet', 'kill', '--kill-whom=main', '--signal', $signal, 'user@*.service');
    }
}

sub reload_reexec_varlink {
    my ($action) = @_;

    if ($action eq "daemon-reload") {
        return varlink_method_invoke('io.systemd.Manager.Reload', '{}');
    } elsif ($action eq "daemon-reexec") {
        return varlink_method_invoke('io.systemd.Manager.Reexecute', '{}');
    } else {
        die("Invalid action for varlink reload/reexec: $action");
    }
}

sub do_reload_reexec {
    my ($action) = @_;

    if (length $ENV{DPKG_ROOT}) {
        return;
    }

    # Prefer varlink, as it can be used with no external dependencies
    # and it's thus safe against apt ordering bugs
    if (reload_reexec_varlink($action) == 0) {
        return;
    } elsif ($use_dbus) {
        reload_reexec_dbus($action);
    } else {
        reload_reexec_signal($action);
    }
}

my $policyhelper = '/usr/sbin/policy-rc.d';
if (length $ENV{DPKG_ROOT}) {
    $policyhelper = $ENV{DPKG_ROOT} . $policyhelper;
}
my @units = @ARGV;
my $action = shift @units;
if (-x $policyhelper) {
    for my $unit (@units) {
        system(qq|$policyhelper $unit "$action"|);

        # 0 or 104 means run
        # 101 means do not run
        my $exitcode = ($? >> 8);
        if ($exitcode == 101) {
            print STDERR "$policyhelper returned 101, not running '" . join(' ', @ARGV) . "'\n";
            exit 0;
        } elsif ($exitcode != 104 && $exitcode != 0) {
            print STDERR "deb-systemd-invoke only supports $policyhelper return codes 0, 101, and 104!\n";
            print STDERR "Got return code $exitcode, ignoring.\n";
        }
    }
}

# If the job is disabled and is not currently running, the job is not started or restarted.
# However, if the job is disabled but has been forced into the running state, we *do* stop
# and restart it since this is expected behaviour for the admin who forced the start.
# We don't autostart static units either.
if ($action eq "start" || $action eq "restart") {
    do_start_restart($action, @units);
} elsif ($action eq "stop" && !$is_system) {
    do_stop_user($action, @units);
} elsif (($action eq "daemon-reload" || $action eq "daemon-reexec")) {
    do_reload_reexec($action);
} else {
    exec('systemctl', @ARGV);
}
